### ISSUE TITLE
Not playing well when moving tiled windows.

### ISSUE THREAD

**Issue by jc9361** [olemartinorg/i3-alternating-layout#23]
This script sets the layout exactly like I wanted. But, it seems to get screwy when trying to re-arrange windows once tiled. Normal behavior of swapping two vertical windows ontop of eachother no longer works. Is there a way around this behavior?

**Comment by olemartinorg** [comment]
I believe this has been mentioned before. This effect is a result of how the script listens for focus events and tries to toggle the current layout (in order to affect new windows).

One way to work around it would be to rebind your commands to move windows and make sure to kill the script and then re-start it again after the move. That way it cannot interfere.

**Comment by jc9361** [comment]
Thank you for your reply, @olemartinorg . I was also thinking killing the script prior to moving windows may help... let me see if I can get this worked out. Would be great to have the auto-layout AND ability to move/re-arrange tiles as expected. Thanks again.
