### ISSUE TITLE
tiling ratio support ?

### ISSUE THREAD

**Issue by aniketfuryrocks** [olemartinorg/i3-alternating-layout#34]
Other tiling window managers have a concept of tiling ratio. 

**Currently**
Windows open with a ratio of 1:1

**Expected**
Windows open with a ratio of a:b where a and b are configurable

**Comment by olemartinorg** [comment]
Is this a question or an issue? Some further explanation would be helpful.

**Comment by aniketfuryrocks** [comment]
> Is this a question or an issue? Some further explanation would be helpful.

question if the feature exists, otherwise a feature request. I would love to contribute but if you can hint me what has to be done in order to achieve the desired result.

**Comment by olemartinorg** [comment]
You're welcome to hack away at the script to see if you find something that'd work for you. The heart of this script is just a few lines long. Pull requests are welcome if you end up with something useful.

Of the top of my head I don't know where I'd begin to implement it, because I still find it hard to envision exactly what you want and in which circumstances it would be needed. If you look at the source code, you'll see this just does horizontal/vertical splitting (when you open a new one) depending on the dimensions of the parent/previous window. I guess you could send a resize command as well, after the split one? See [the i3 manual here](https://i3wm.org/docs/userguide.html#resizingconfig). Good luck!

**Comment by aniketfuryrocks** [comment]
i'll close this issue for now,
